import type { Block, TodoAndChildren } from "../src/types.js";

export const data: Block[] = [
  {
    object: "block",
    id: "1",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "heading_1",
    heading_1: {
      rich_text: [{ plain_text: "To do" }],
      is_toggleable: false,
      color: "default",
    },
  },
  {
    object: "block",
    id: "2",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: true, color: "default" },
  },
  {
    object: "block",
    id: "3",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "4",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "5",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "27f5cd2c-ab6b-80ad-a140-cb7aac8dfe70",
    parent: {
      type: "page_id",
      page_id: "27f5cd2c-ab6b-8090-a7f8-cd59088a3058",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "heading_1",
    heading_1: { rich_text: [Array], is_toggleable: false, color: "default" },
  },
];

export const dataWithChildren: Block[] = [
  {
    object: "block",
    id: "1",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "heading_1",
    heading_1: {
      rich_text: [{ plain_text: "To do" }],
      is_toggleable: false,
      color: "default",
    },
  },
  {
    object: "block",
    id: "2",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: true, color: "default" },
  },
  {
    object: "block",
    id: "3",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "4",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "5",
    parent: {
      type: "page_id",
      page_id: "other-page-id",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "to_do",
    to_do: { rich_text: [Array], checked: false, color: "default" },
  },
  {
    object: "block",
    id: "27f5cd2c-ab6b-80ad-a140-cb7aac8dfe70",
    parent: {
      type: "page_id",
      page_id: "27f5cd2c-ab6b-8090-a7f8-cd59088a3058",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: true,
    archived: false,
    in_trash: false,
    type: "heading_1",
    heading_1: { rich_text: [Array], is_toggleable: false, color: "default" },
  },
];

export const children: Block[] = [
  {
    object: "block",
    id: "6",
    parent: {
      type: "block_id",
      page_id: "4",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "paragraph",
    paragraph: { rich_text: [Array], color: "default" },
  },
  {
    object: "block",
    id: "7",
    parent: {
      type: "block_id",
      page_id: "4",
    },
    created_time: new Date(),
    last_edited_time: new Date(),
    created_by: { object: "user", id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52" },
    last_edited_by: {
      object: "user",
      id: "0f4e7bc4-507e-43d0-a1d1-5796fd61aa52",
    },
    has_children: false,
    archived: false,
    in_trash: false,
    type: "paragraph",
    paragraph: { rich_text: [Array], color: "default" },
  },
];

export const toDo: TodoAndChildren[] = [
  {
    children: [],
    todos: data[0]!,
  },
];
