// Generated by https://quicktype.io

export interface NotionDatabase {
  object: string;
  id: string;
  title: Title[];
  description: any[];
  parent: Parent;
  is_inline: boolean;
  in_trash: boolean;
  is_locked: boolean;
  created_time: Date;
  last_edited_time: Date;
  data_sources: DataSource[];
  icon: null;
  cover: null;
  url: string;
  public_url: null;
  request_id: string;
}

export interface DataSource {
  id: string;
  name: string;
}

export interface Parent {
  type: string;
  page_id: string;
}

export interface Title {
  type: string;
  text: Annotations;
  annotations: Annotations;
  plain_text: string;
  href: null;
}

export interface Annotations {}

// Generated by https://quicktype.io

export interface NotionDatasource {
  object: string;
  results: Block[];
  next_cursor: string;
  has_more: boolean;
  type: string;
  page_or_data_source: PageOrDataSource;
  request_id: string;
}

export interface PageOrDataSource {}

export type TodoAndChildren = {
  todos: Block;
  children: TodoAndChildren[];
};

export interface Block {
  object: string;
  id: string;
  parent: Parent;
  created_time: Date;
  last_edited_time: Date;
  created_by: TedBy;
  last_edited_by: TedBy;
  has_children: boolean;
  archived: boolean;
  in_trash: boolean;
  type: string;
  [key: string]: any;
}

export interface TedBy {
  object: string;
  id: string;
}
