// Generated by https://quicktype.io

export interface NotionDatabase {
  object: string;
  id: string;
  title: Title[];
  description: any[];
  parent: Parent;
  is_inline: boolean;
  in_trash: boolean;
  is_locked: boolean;
  created_time: Date;
  last_edited_time: Date;
  data_sources: DataSource[];
  icon: null;
  cover: null;
  url: string;
  public_url: null;
  request_id: string;
}

export interface DataSource {
  id: string;
  name: string;
}

export interface Parent {
  type: string;
  page_id: string;
}

export interface Title {
  type: string;
  text: Annotations;
  annotations: Annotations;
  plain_text: string;
  href: null;
}

export interface Annotations {}

// Generated by https://quicktype.io

export interface NotionDatasource {
  object: string;
  results: Result[];
  next_cursor: string;
  has_more: boolean;
  type: string;
  page_or_data_source: PageOrDataSource;
  request_id: string;
}

export interface PageOrDataSource {}

export interface Result {
  object: string;
  id: string;
  created_time: Date;
  last_edited_time: Date;
  created_by: PageOrDataSource;
  last_edited_by: PageOrDataSource;
  cover: null;
  icon: PageOrDataSource;
  parent: PageOrDataSource;
  archived: boolean;
  in_trash: boolean;
  is_locked: boolean;
  properties: PageOrDataSource;
  url: string;
  public_url: null;
}
